name: test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Dub Tests
    strategy:
      fail-fast: false
      matrix:
        dc:
          - dmd-latest
          - ldc-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run build
        run: dub build
      - name: Run tests
        run: dub -q test --coverage
      - uses: codecov/codecov-action@v2
